// Organized group day trips — who runs recurring trip programs for
// Chicagoland seniors, organized by who runs them (park district,
// township/senior center, or national/regional tour company). Every entry
// is a real program verified against its own official site; anything not
// confirmed is left out of the field or flagged in verifyNotes rather than
// guessed. No dated departures — every entry links to the organizer's own
// live schedule instead, since specific trips expire fast.
//
// Dedup discipline: most of these organizers already exist as Listing rows
// in the DB (built up over many area-research waves). Where that's true,
// existingListingSlug cross-links to that listing instead of creating a
// duplicate. Only organizations with no existing DB listing (the national
// tour companies) are wholly new here.
//
// tags is intentionally unpopulated — a nullable field reserved for a
// future interest-based filter (Nature/Food/Beach/etc.) once there's
// enough volume to justify it. Do not build filter UI against this yet.
import { AFFILIATES } from "./affiliates";

export type County = "Cook" | "DuPage" | "Lake" | "Will" | "Kane" | "Kendall" | "McHenry";

export type OrganizedTripProvider = {
  slug: string;
  name: string;
  group: "park-district" | "township-senior-center" | "tour-company";
  // Undefined only for tour-company entries — they aren't geographic.
  county?: County;
  existingListingSlug?: string;
  sourceUrl: string;
  blurb: string;
  departure?: string;
  cost: string;
  whoCanJoin: string;
  howToSignUp: string;
  bookingUrl?: string;
  tags?: string[] | null;
  verifyNotes?: string[];
};

export const ORGANIZED_TRIP_PROVIDERS: OrganizedTripProvider[] = [
  // ---------- Park District senior trips ----------
  {
    slug: "bolingbrook-park-district",
    name: "Bolingbrook Park District — Adult Trips",
    group: "park-district",
    county: "Will",
    existingListingSlug: "bolingbrook-park-district-adult-trips",
    sourceUrl: "https://bolingbrookparks.org/programs/trips/",
    blurb:
      "Coach bus trips ranging from single-day outings (theater shows) to multi-day tours (a past Smoky Mountains/Pigeon Forge trip).",
    cost: "Varies by trip — not published as a general rate",
    whoCanJoin: "Open registration; discounted Resident ID pricing for Bolingbrook residents; early access for Parkie's E-Club members",
    howToSignUp:
      "Register online, or drop off/mail registration to Annerino Community Center (201 Recreation Drive) or the Recreation & Aquatic Complex (200 S. Lindsey Lane)",
    tags: null,
    verifyNotes: ["Exact per-trip cost and departure point weren't published generally — check the current trip flyer."],
  },
  {
    slug: "crystal-lake-park-district",
    name: "Crystal Lake Park District — Day Trips",
    group: "park-district",
    county: "McHenry",
    existingListingSlug: "crystal-lake-park-district-day-trips",
    sourceUrl: "https://www.crystallakeparks.org/active-adults",
    blurb:
      "Weekly day trips to performances, concerts, sporting events, shopping, casinos, cultural tours, and restaurant dining.",
    departure: "Varies by trip, based on group size — not a single fixed location",
    cost: "Past examples: $10-13 for a lunch-style trip; varies by destination",
    whoCanJoin: "Open registration, no residency requirement stated",
    howToSignUp:
      "Register at the Administrative Office (One East Crystal Lake Ave) or online at crystallakeparks.org; questions to Jennifer Peterson, 815-459-0680",
    tags: null,
  },
  {
    slug: "wood-dale-park-district",
    name: "Wood Dale Park District — Adult & Senior Trips",
    group: "park-district",
    county: "DuPage",
    existingListingSlug: "wood-dale-park-district-senior-programs-trips",
    sourceUrl: "https://www.wdparks.org/programs/adult-senior-trips/",
    blurb: "Day trips plus occasional overnight trips to restaurants, performances, and special events.",
    cost: "Resident/non-resident tiered pricing per trip (past examples: $20R/$24NR, $14R/$16NR); some longer trips require a $50 deposit",
    whoCanJoin: "Open to residents and non-residents at different price tiers",
    howToSignUp: "Register online through the Park District's registration system at wdparks.org",
    tags: null,
    verifyNotes: ["Exact departure point wasn't stated — confirm per trip."],
  },
  {
    slug: "rolling-meadows-park-district",
    name: "Rolling Meadows Park District — Adult Activity Center",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "adult-activity-center-rolling-meadows-park-district",
    sourceUrl: "https://rmparks.org/adult-activity-center",
    blurb: "A membership-based senior center whose membership includes discounts on day trips and overnight trips.",
    departure: "Based out of the Community Center, 3705 Pheasant Drive (Door K)",
    cost: "Membership $30/yr residents, $35/yr non-residents (discounted $15/$20 for ages 95+); trip fees cover transportation only, separate from destination costs",
    whoCanJoin: "Open to residents and non-residents at different membership rates",
    howToSignUp: "Call 847-818-3209 or email awilford@rmparks.org; membership year runs May 1-April 30",
    tags: null,
    verifyNotes: ["Membership pricing found dates to 2022 — confirm current rates before joining."],
  },
  {
    slug: "st-charles-park-district",
    name: "St. Charles Park District — Active Adult Center",
    group: "park-district",
    county: "Kane",
    existingListingSlug: "st-charles-park-district-active-adult-center",
    sourceUrl: "https://www.stcparks.org/aac/",
    blurb:
      "A 50+ activity center running guided walks and trips to theaters and culturally interesting destinations, alongside lively lunches with live entertainment.",
    departure: "Based out of the Pottawatomie Community Center, 8 North Ave, St. Charles",
    cost: "Annual membership $15 residents / $23 non-residents, or $5 daily guest fee; trip costs vary separately",
    whoCanJoin: "Ages 50+; open to residents and non-residents at different rates",
    howToSignUp: "Contact Adult Activity Supervisor Lynne Yuill, 630-513-4324",
    tags: null,
  },

  // ---------- Township & senior center trips ----------
  {
    slug: "forest-park-howard-mohr",
    name: "Howard Mohr Community Center — Senior Citizens Club (Forest Park)",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "howard-mohr-community-center-senior-citizens-club",
    sourceUrl: "https://www.forestpark.net/dfp/departments/community-center/",
    blurb: "Weekly day trips scheduled out of the Center, plus dedicated Monday and Thursday shopping trips for residents 55+.",
    departure: "Howard Mohr Community Center, 7640 Jackson Blvd, Forest Park (presumed departure point, not explicitly confirmed)",
    cost: "Verify — see official site (membership fee not published)",
    whoCanJoin: "Membership-based Senior Citizens Club, application through the Village",
    howToSignUp: "Contact Community Center Director Karen Dylewski, 708-771-7737 or kdylewski@forestpark.net",
    tags: null,
    verifyNotes: ["Membership fee and exact trip departure point weren't confirmed on official pages."],
  },
  {
    slug: "maine-township-mainestreamers",
    name: "Maine Township — MaineStreamers",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "maine-township-mainestreamers",
    sourceUrl: "https://mainetown.com/departments/mainestreamers/",
    blurb: "A social and enrichment group for residents 55+ combining fitness classes, workshops, and organized day trips.",
    cost: "Membership is free; individual day trips have their own separate costs",
    whoCanJoin: "Maine Township residents 55+",
    howToSignUp: "Join online (add \"Join MaineStreamers\" through the Township's catalog) or call/visit the Township office, 847-297-2510",
    tags: null,
    verifyNotes: ["Per-trip departure location wasn't stated on official pages."],
  },
  {
    slug: "orland-township-senior-services",
    name: "Orland Township — Senior Trips",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "orland-township-senior-services",
    sourceUrl: "https://orlandtownship.org/senior-trips/",
    blurb: "Day and overnight trips via reserved-seat deluxe motor coach, tickets sold first-come-first-served when they go on sale.",
    cost: "Varies by trip — past examples around $15-30 for residents",
    whoCanJoin:
      "Requires a free Township resident ID number (proof of residency required) before purchasing trip tickets; tickets limited to 2 per person, non-transferable",
    howToSignUp: "Call (708) 403-4222, Mon-Fri 9am-3pm, for the current trip schedule and ticket sale dates",
    tags: null,
    verifyNotes: ["Some trips appear resident-priced based on past examples — confirm non-resident eligibility before planning a trip."],
  },
  {
    slug: "hanover-township-senior-center",
    name: "Hanover Township — Senior Center",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "hanover-township-senior-center",
    sourceUrl: "https://www.hanover-township.org/departments/aging-services/life-enrichment",
    blurb: "Enrichment programming that includes local day trips alongside fitness classes, tech classes, and cultural presentations.",
    departure: "Hanover Township Senior Center, 240 S IL Route 59, Bartlett (presumed departure point, not explicitly confirmed)",
    cost: "Verify — see official site",
    whoCanJoin: "Verify — see official site (serves Bartlett, Elgin, Hanover Park, Hoffman Estates, Schaumburg, Streamwood)",
    howToSignUp: "Call (630) 483-5600",
    tags: null,
    verifyNotes: ["Trip costs and eligibility weren't confirmed on official pages — call ahead."],
  },

  // ---------- More Park District senior trips (county sweep) ----------
  {
    slug: "elmhurst-park-district",
    name: "Elmhurst Park District — Trips",
    group: "park-district",
    county: "DuPage",
    sourceUrl: "https://www.epd.org/programs/trips",
    blurb: "Motor coach day trips — a past example included a Lake Geneva cruise with a sit-down lunch and shopping time downtown.",
    departure: "Mary E. Kies Recreation Center, 155 E. St. Charles Rd., Elmhurst, unless a trip states otherwise",
    cost: "Varies by trip — fee typically includes transportation and a meal where noted",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Register at epd.org/programs/trips or through the Mary E. Kies Recreation Center",
    tags: null,
  },
  {
    slug: "downers-grove-park-district",
    name: "Downers Grove Park District — Scarlett Bloomers",
    group: "park-district",
    county: "DuPage",
    sourceUrl: "https://www.dgparks.org/lincoln-center-active-adults",
    blurb: "A 55+ social group running monthly themed luncheons, luncheon trips, weekly game clubs, and occasional overnight parties.",
    departure: "Lincoln Center — meetings held the 3rd Monday of each month, 1-3pm",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Contact the Lincoln Center Active Adults program at dgparks.org",
    tags: null,
  },
  {
    slug: "wheaton-park-district",
    name: "Wheaton Park District — Day Trips",
    group: "park-district",
    county: "DuPage",
    sourceUrl: "https://wheatonparkdistrict.com/day-trips/",
    blurb: "Motor-coach day trips where \"the district does all the planning\" — the coach picks riders up and nothing else is required of participants.",
    departure: "Mary Lubko Center, in downtown Wheaton's Memorial Park",
    cost: "Varies — see current schedule (published in the quarterly \"Time of Your Life\" newsletter)",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call the Mary Lubko Center, 630-665-1415, or visit in person",
    tags: null,
  },
  {
    slug: "schaumburg-park-district",
    name: "Schaumburg Park District — Senior Trips",
    group: "park-district",
    county: "Cook",
    sourceUrl: "https://www.parkfun.com/programs-events/seniors",
    blurb: "Day excursions to destinations like Wrigley Field, casinos, and theater shows — a genuinely distinct organization from Schaumburg Township's senior services.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 847-490-7026 or view the current program guide at parkfun.com",
    tags: null,
    verifyNotes: ["Whether trips use the district's own bus or a charter service wasn't confirmed."],
  },
  {
    slug: "elk-grove-park-district",
    name: "Elk Grove Park District — Trips and Outings",
    group: "park-district",
    county: "Cook",
    sourceUrl: "https://elkgroveparks.org/trips",
    blurb: "Outings open to adults 18+ (21+ for gambling trips); Senior Center members get the resident rate on all trips.",
    departure: "South Pavilion Parking Lot, 1000 Wellington Ave., Elk Grove Village",
    cost: "Varies — see current Program Guide, The Buzz Newsletter, or Trips Trifold Brochure",
    whoCanJoin: "Open to adults 18+ (21+ for gambling-destination trips); Senior Center members receive resident pricing",
    howToSignUp: "Call 847-364-7224",
    tags: null,
  },
  {
    slug: "park-district-of-oak-park",
    name: "Park District of Oak Park — Lifelong Learning",
    group: "park-district",
    county: "Cook",
    sourceUrl: "https://pdop.org/programs/lifelong-learning/",
    blurb: "Trips and educational programming for adults 50+, run in partnership with the Senior Citizens' Center of Oak Park and River Forest.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Adults 50+",
    howToSignUp: "See pdop.org or contact Senior & Disability Services of Oak Park and River Forest Townships, 708-383-8060",
    tags: null,
  },
  {
    slug: "oak-lawn-park-district",
    name: "Oak Lawn Park District — Trips",
    group: "park-district",
    county: "Cook",
    sourceUrl: "https://www.olparks.com/programs/trips",
    blurb: "Senior day trips including guided hikes (Starved Rock), factory/museum tours, and city excursions to Museum Campus.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call the Oak View Center, 708-857-2200, or visit olparks.com/contact-us",
    tags: null,
  },
  {
    slug: "homewood-flossmoor-park-district",
    name: "Homewood-Flossmoor Park District — Adult & Senior Programs",
    group: "park-district",
    county: "Cook",
    sourceUrl: "https://hfparks.com/vipprograms/",
    blurb: "Adult and senior programming out of the Irwin Community Center, serving Homewood and Flossmoor.",
    departure: "Irwin Community Center, 18120 S. Highland Ave., Homewood",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 708-799-1323 or see hfparks.com",
    tags: null,
    verifyNotes: ["Day-trip specifics weren't itemized on official pages — confirm current trip offerings directly."],
  },
  {
    slug: "glen-ellyn-park-district",
    name: "Glen Ellyn Park District — Trips",
    group: "park-district",
    county: "DuPage",
    sourceUrl: "https://gepark.org/adults-seniors/",
    blurb: "Trips throughout the year including city breaks and casino visits, serving Glen Ellyn, Wheaton, Carol Stream, Lombard, and Glendale Heights residents.",
    cost: "Varies — see current schedule; registration is first-come, first-served",
    whoCanJoin: "Ages 55+",
    howToSignUp: "See gepark.org/adults-seniors/",
    tags: null,
  },
  {
    slug: "lombard-park-district",
    name: "Lombard Park District — Active Adults",
    group: "park-district",
    county: "DuPage",
    sourceUrl: "https://lombardparks.com/activeadults/",
    blurb: "Day trips and several week-long trips alongside senior clubs, fitness classes, and educational workshops.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "See lombardparks.com/activeadults/",
    tags: null,
  },
  {
    slug: "joliet-park-district",
    name: "Joliet Park District — Office of Citizens Services",
    group: "park-district",
    county: "Will",
    sourceUrl: "https://jolietpark.org/trips",
    blurb: "Full-day guided tours (a past example: Indiana Amish Country) plus shorter local outings, run through the Office of Citizens Services.",
    departure: "Departs from the Community Center for local trips",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 708-422-8766",
    tags: null,
  },
  {
    slug: "plainfield-park-district",
    name: "Plainfield Park District — Active Adults",
    group: "park-district",
    county: "Will",
    sourceUrl: "https://www.plfdparks.org/programs-events/active-adults/",
    blurb: "Day trips to regional attractions plus seasonal lunch events, fitness/yoga classes, and games; sometimes co-sponsored with neighboring park districts.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "See plfdparks.org/programs-events/active-adults/ or sign up for their e-newsletter",
    tags: null,
  },
  {
    slug: "fox-valley-park-district",
    name: "Fox Valley Park District (Aurora) — Tours, Visits & Shows",
    group: "park-district",
    county: "Kane",
    sourceUrl: "https://www.foxvalleyparkdistrict.org/programs-events/tours-visits-shows/",
    blurb: "Trips in a 25-passenger bus with an onboard restroom, to lake/river cruises, casinos, theatre, sporting events, gardens, festivals, wineries, and shopping.",
    cost: "Varies — described as convenient and affordable, exact pricing not published generally",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "See foxvalleyparkdistrict.org/programs-events/tours-visits-shows/",
    tags: null,
  },
  {
    slug: "batavia-park-district",
    name: "Batavia Park District — Trips",
    group: "park-district",
    county: "Kane",
    sourceUrl: "https://bataviaparks.org/program/trips/",
    blurb: "Rotating seasonal trips (culinary, history, sightseeing, theater, and more) rated by walking difficulty from Easy to Challenging, often run in cooperation with neighboring park districts.",
    departure: "Eastside Community Center parking lot; arrive at least 15 minutes before departure",
    cost: "Fees cover transportation; lunch and admission may be included depending on the trip",
    whoCanJoin: "Open to all — trips are run in cooperation with area park districts",
    howToSignUp: "Call 630-879-5235 or email Recreation Supervisor Elisha Sharp, elishas@bataviaparks.org",
    tags: null,
  },
  {
    slug: "waukegan-park-district",
    name: "Waukegan Park District — Trips",
    group: "park-district",
    county: "Lake",
    sourceUrl: "https://www.waukeganparks.org/",
    blurb: "Trips are part of the district's broader year-round programming for all ages, alongside athletics, fitness, and special events.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "See waukeganparks.org",
    tags: null,
    verifyNotes: ["Senior-specific trip details weren't itemized on official pages — confirm current offerings directly."],
  },

  // ---------- More Township & senior center trips (county sweep) ----------
  {
    slug: "tinley-park-senior-center",
    name: "Tinley Park Senior Center",
    group: "township-senior-center",
    county: "Cook",
    sourceUrl: "https://www.tinleypark.org/residents/senior_information.php",
    blurb: "Bus excursions by deluxe motor coach (past example: a Four Winds Casino trip, $60/person including a slot and food credit); details run in the monthly newsletter.",
    departure: "Tinley Park Senior Center, 17355 S. 68th Court, Tinley Park",
    cost: "Varies by trip — past example around $60/person including onboard credits",
    whoCanJoin: "Ages 55+",
    howToSignUp: "Contact Marie Ryan, mryan@tinleypark.org or (708) 444-5011, or call the Senior Center at (708) 444-5150 / seniorcenter@tinleypark.org",
    tags: null,
  },
  {
    slug: "waukegan-township-patricia-jones-center",
    name: "Waukegan Township — Patricia A. Jones Center",
    group: "township-senior-center",
    county: "Lake",
    sourceUrl: "https://www.waukegantownship.com/165/Patricia-A-Jones-Center",
    blurb: "Trips and events for adults 55+ alongside health, fitness, and transportation services; open to any adult, with children welcome on some excursions.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Any adult; some trips welcome accompanied children",
    howToSignUp: "See waukegantownship.com/165/Patricia-A-Jones-Center",
    tags: null,
  },

  // ---------- Guided tour companies ----------
  {
    slug: "road-scholar",
    name: "Road Scholar",
    group: "tour-company",
    sourceUrl: "https://www.roadscholar.org/",
    blurb:
      "A nonprofit educational travel program for ages 50+. Verified: their programs, including Chicago-area ones, are multi-day (shortest run about 3 days with lodging) — not single-day excursions.",
    cost: "Shorter 3-5 day domestic programs can run under $1,000/person; longer international trips cost more",
    whoCanJoin: "Adults 50+ (and a companion), nationwide",
    howToSignUp: "Browse and book directly at roadscholar.org",
    bookingUrl: AFFILIATES.roadScholar.url, // AFFILIATE: replace with Road Scholar link (see lib/affiliates.ts)
    tags: null,
    verifyNotes: ["Confirmed this is not a day-trip provider — shortest programs are 3 days minimum with lodging included."],
  },
  {
    slug: "jones-travel",
    name: "Jones Travel",
    group: "tour-company",
    sourceUrl: "https://www.jonestravel.com/senior-travel.html",
    blurb:
      "A senior motorcoach service running since 1969, based in Elkhorn, WI, with regular trips into Chicago, Milwaukee, Madison, Wisconsin Dells, and Rockford. Fleet includes handicap-accessible coaches.",
    cost: "Not published — request a quote",
    whoCanJoin: "Open to the public",
    howToSignUp: "Call 800-236-3160 or request a quote on their site; current trip lineup is under Popular Trips",
    tags: null,
  },
  {
    slug: "cardinal-buses",
    name: "Cardinal Buses",
    group: "tour-company",
    sourceUrl: "https://www.cardinalbuses.com/",
    blurb:
      "A motorcoach company operating since 1923 out of Indiana and Michigan, known locally for Amish-country day tours and popular with senior and retiree groups. Coaches can be lift-equipped and accommodate wheelchairs, scooters, and rollators on request.",
    cost: "Not published — request a quote",
    whoCanJoin: "Open to the public",
    howToSignUp: "Call 800-348-7487 or email info@cardinalbuses.com — mention accessibility needs when booking",
    tags: null,
  },
  {
    slug: "mayflower-tours",
    name: "Mayflower Tours",
    group: "tour-company",
    sourceUrl: "https://www.mayflowercruisesandtours.com/",
    blurb:
      "An Illinois-based tour operator (Downers Grove) running since 1979, with 100+ itineraries including \"Motorcoach Holiday\" tours and small-ship cruises, each with a professional Tour Manager on board.",
    cost: "Varies by trip — see current offerings",
    whoCanJoin: "Open to the public",
    howToSignUp: "Call 800-323-7604 or browse tours at mayflowercruisesandtours.com",
    tags: null,
    verifyNotes: [
      "Their branding centers on multi-day 'Motorcoach Holiday' tours rather than single-day excursions — confirm whether any single-day Chicago-area trips are currently offered before assuming so.",
    ],
  },
  {
    slug: "diamond-tours",
    name: "Diamond Tours",
    group: "tour-company",
    sourceUrl: "https://www.diamondtours.com/",
    blurb:
      "A national motorcoach operator (38+ years) working with 55+ senior citizen groups, with coaches seating 54+ and most breakfasts/dinners included.",
    cost: "Varies by trip — no fee or deposit required to book, per their site",
    whoCanJoin: "Groups, including 55+ senior citizen groups",
    howToSignUp: "Call 800-336-5711 with preferred travel dates",
    tags: null,
    verifyNotes: [
      "Confirmed tours to Chicago as a destination; did not confirm they run Chicago-departure day trips specifically for local seniors — likely more relevant as a national group-tour option.",
    ],
  },

  // ---------- Bulk-imported from existing DB Listings (county sweep) ----------
  // These organizations were already verified and added to the site's main
  // Listing table during earlier area-research waves this session. Rather
  // than re-researching each from scratch (duplicating verified work) or
  // re-typing details by hand (risking transcription drift from the DB),
  // these entries were generated directly from that Listing data: name,
  // sourceUrl, phone, and residency requirement (residentRequired) all
  // trace to the existing row, linked via existingListingSlug. Cost is
  // deliberately generic ("Varies — see current schedule") for all of
  // these — the DB's cost field describes the venue's overall program
  // cost (often FREE membership), not the trip-specific fee, and the task
  // brief explicitly says never default an unconfirmed cost to "Free."
  {
    slug: "bulk-highland-park-senior-center-city-of-highland-park-division-of-senior-services",
    name: "Highland Park Senior Center (City of Highland Park Division of Senior Services)",
    group: "township-senior-center",
    county: "Lake",
    existingListingSlug: "highland-park-senior-center-city-division-senior-services",
    sourceUrl: "https://www.cityhpil.com/resident/senior_center/index.php",
    blurb:
      "One of Highland Park's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call 847.432.4110 — Register via the online member portal or in person; contact Laura Frey, Manager of Senior Services, at lfrey@cityhpil.com.",
    tags: null,
  },
  {
    slug: "bulk-crystal-lake-park-district-grand-oaks-active-senior-center",
    name: "Crystal Lake Park District Grand Oaks Active Senior Center",
    group: "park-district",
    county: "McHenry",
    existingListingSlug: "crystal-lake-grand-oaks-active-senior-center",
    sourceUrl: "https://www.crystallakeparks.org/active-adults",
    blurb:
      "One of Crystal Lake's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call (815) 459-0680 ext. 1219",
    tags: null,
  },
  {
    slug: "bulk-oswego-senior-community-center",
    name: "Oswego Senior & Community Center",
    group: "township-senior-center",
    county: "Kendall",
    existingListingSlug: "oswego-senior-community-center",
    sourceUrl: "https://oswegoseniorcenter.org/",
    blurb:
      "One of Oswego's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 630-554-5602",
    tags: null,
  },
  {
    slug: "bulk-calumet-township-senior-service-center",
    name: "Calumet Township Senior Service Center",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "calumet-township-senior-service-center",
    sourceUrl: "https://calumettownshipil.com/services/",
    blurb:
      "One of Calumet Park's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 708-388-6606 — Lunch tickets must be purchased before 11:45 AM",
    tags: null,
  },
  {
    slug: "bulk-itasca-senior-club",
    name: "Itasca Senior Club",
    group: "township-senior-center",
    county: "DuPage",
    existingListingSlug: "itasca-senior-club",
    sourceUrl: "https://www.itascaparkdistrict.com/236/Adults-Senior-Happenings",
    blurb:
      "One of Itasca's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 630-773-2257 — Contact staff directly to join",
    tags: null,
  },
  {
    slug: "bulk-naperville-park-district-active-adults",
    name: "Naperville Park District Active Adults",
    group: "park-district",
    county: "DuPage",
    existingListingSlug: "naperville-park-district-active-adults",
    sourceUrl: "https://napervilleparks.org/activeadults",
    blurb:
      "One of Naperville's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 630-848-5000 — Register at napervilleparks.org/programguides or by phone",
    tags: null,
  },
  {
    slug: "bulk-park-district-of-la-grange-senior-programs",
    name: "Park District of La Grange — Senior Programs",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "park-district-of-la-grange-senior-programs",
    sourceUrl: "https://pdlg.org/our-programs/senior-programs",
    blurb:
      "One of La Grange's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call 708-352-1762 — Verify — see official site for current schedule (site blocked automated verification)",
    tags: null,
  },
  {
    slug: "bulk-active-adult-activities-age-55-park-ridge-park-district",
    name: "Active Adult Activities (Age 55+) — Park Ridge Park District",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "active-adult-activities-age-55-plus-park-ridge-park-district",
    sourceUrl: "https://www.prparks.org/Activities/General-Interest/Active-Adult-Activities-Age-55-",
    blurb:
      "One of Park Ridge's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call 847-692-5127 — Registration deadlines vary by program, typically 1-2 weeks prior; register online or at the Centennial Activity Center",
    tags: null,
  },
  {
    slug: "bulk-addison-park-district-active-adults-senior-club",
    name: "Addison Park District Active Adults & Senior Club",
    group: "park-district",
    county: "DuPage",
    existingListingSlug: "addison-park-district-active-adults-senior-club",
    sourceUrl: "https://addisonparks.org/active-adults-club/",
    blurb:
      "One of Addison's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call (630) 233-7275 option 2 — Annual membership plus online registration for individual trips/events",
    tags: null,
  },
  {
    slug: "bulk-clarendon-hills-park-district-60-social-club",
    name: "Clarendon Hills Park District 60+ Social Club",
    group: "park-district",
    county: "DuPage",
    existingListingSlug: "clarendon-hills-park-district-60-plus-social-club",
    sourceUrl: "https://www.clarendonhillsparkdistrict.org/60-plus-social-club/",
    blurb:
      "One of Clarendon Hills's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 630.323.2626 — Activity-specific online registration; no monthly membership fee",
    tags: null,
  },
  {
    slug: "bulk-leyden-township-senior-services",
    name: "Leyden Township Senior Services",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "leyden-township-senior-services",
    sourceUrl: "https://www.leydentownship.com/223/Senior-Services",
    blurb:
      "One of Franklin Park's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Residents only (based on listing data)",
    howToSignUp: "Call 847-455-8616 ext. 5119",
    tags: null,
  },
  {
    slug: "bulk-wheeling-park-district-active-adults",
    name: "Wheeling Park District — Active Adults",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "wheeling-park-district-active-adults",
    sourceUrl: "https://www.wheelingparkdistrict.com/active-adults/",
    blurb:
      "One of Wheeling's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call 847-465-3333 — Verify — see official site for current schedule and costs (site blocked automated verification)",
    tags: null,
  },
  {
    slug: "bulk-active-adults-prospect-heights-park-district",
    name: "Active Adults — Prospect Heights Park District",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "active-adults-prospect-heights-park-district",
    sourceUrl: "https://phparks.org/active-adults/",
    blurb:
      "One of Prospect Heights's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call (847) 666-4875 — Join mailing list for trip offerings; contact Marci Glinski",
    tags: null,
  },
  {
    slug: "bulk-olympia-fields-park-district-senior-programs",
    name: "Olympia Fields Park District Senior Programs",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "olympia-fields-park-district-senior-programs",
    sourceUrl: "https://www.ofparks.org/mahjongg-scrabble",
    blurb:
      "One of Olympia Fields's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call 708-481-7313 — Not required for Mah Jongg/Scrabble; online registration required for van trips and Tai Chi",
    tags: null,
  },
  {
    slug: "bulk-arlington-heights-park-district-active-adult-program",
    name: "Arlington Heights Park District Active Adult Program",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "arlington-heights-park-district-active-adults",
    sourceUrl: "https://www.ahpd.org/programs/seniors/",
    blurb:
      "One of Arlington Heights's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 847-797-5341 — Register online at ahpd.org or in person; financial assistance available",
    tags: null,
  },
  {
    slug: "bulk-levy-senior-center",
    name: "Levy Senior Center",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "levy-senior-center-evanston",
    sourceUrl: "https://www.cityofevanston.org/departments/prcs/facilities/levy_senior_center/programs_info.php",
    blurb:
      "One of Evanston's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call 847-448-8250 — Register through the City of Evanston Parks & Recreation program guide, or call 847-448-4311 / 311",
    tags: null,
  },
  {
    slug: "bulk-round-lake-area-park-district-senior-activities-50",
    name: "Round Lake Area Park District Senior Activities (50+)",
    group: "park-district",
    county: "Lake",
    existingListingSlug: "round-lake-area-park-district-senior-activities-50-plus",
    sourceUrl: "https://www.rlapd.org/senior-center",
    blurb:
      "One of Round Lake's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call (847) 546-8558 — Register online at apm.activecommunities.com/roundlakeareaparkdistrict/, or contact Jodi Schultz at jodi_schultz@rlapd.org for lunch program details.",
    tags: null,
  },
  {
    slug: "bulk-mundelein-park-recreation-district-active-adults",
    name: "Mundelein Park & Recreation District Active Adults",
    group: "park-district",
    county: "Lake",
    existingListingSlug: "mundelein-park-district-active-adults",
    sourceUrl: "https://www.mundeleinparks.org/programs/active-adults/",
    blurb:
      "One of Mundelein's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call (847) 566-4790",
    tags: null,
  },
  {
    slug: "bulk-prime-time-club-pinochle-club-55-community-park-district",
    name: "Prime Time Club & Pinochle Club 55+ (Community Park District)",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "prime-time-club-pinochle-club-55-plus-community-park-district",
    sourceUrl: "https://www.communityparkdistrict.org/programs/adults/senior-programming",
    blurb:
      "One of La Grange Park's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call (708) 354-4580 — No registration required for Pinochle Club; Prime Time Club is a paid annual membership; day trips require registration",
    tags: null,
  },
  {
    slug: "bulk-veterans-park-district-active-adults-seniors",
    name: "Veterans Park District Active Adults & Seniors",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "veterans-park-district-active-adults-seniors",
    sourceUrl: "https://vpdpark.org/active-adults/",
    blurb:
      "One of Northlake's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp: "Call (708) 343-5270 — Required in advance for most events (email frontdesk@vpdpark.org)",
    tags: null,
  },
  {
    slug: "bulk-antioch-township-senior-services-antioch-senior-center",
    name: "Antioch Township Senior Services (Antioch Senior Center)",
    group: "township-senior-center",
    county: "Lake",
    existingListingSlug: "antioch-township-senior-services-antioch-senior-center",
    sourceUrl: "https://www.antiochtownshipil.gov/senior_services/index.php",
    blurb:
      "One of Antioch's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call (847) 395-3378 — Contact the Senior Services office directly; membership available to make participation easier.",
    tags: null,
  },
  {
    slug: "bulk-dickinson-hall-senior-center",
    name: "Dickinson Hall Senior Center",
    group: "township-senior-center",
    county: "Lake",
    existingListingSlug: "dickinson-hall-senior-center",
    sourceUrl: "https://www.cityoflakeforest.com/departments/dickinson_hall/programs.php",
    blurb:
      "One of Lake Forest's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call (847) 234-2600 — Contact Dickinson Hall directly; see the bi-monthly Newsbrief newsletter for current schedules.",
    tags: null,
  },
  {
    slug: "bulk-north-shore-senior-center",
    name: "North Shore Senior Center",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "north-shore-senior-center",
    sourceUrl: "https://www.nssc.org/lifelong-learning-programs/membership/",
    blurb:
      "One of Northfield's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call 847.784.6000 (Lifelong Learning: 847.784.6030) — Registration required for all Lifelong Learning programs; enroll online through their registration portal",
    tags: null,
  },
  {
    slug: "bulk-skokie-park-district-active-adults",
    name: "Skokie Park District Active Adults",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "skokie-park-district-active-adults",
    sourceUrl: "https://www.skokieparks.org/active-adults/",
    blurb:
      "One of Skokie's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "See official site for current schedule and registration",
    tags: null,
  },
  {
    slug: "bulk-ela-50-adult-senior-programs",
    name: "Ela 50+ Adult & Senior Programs",
    group: "township-senior-center",
    county: "Lake",
    existingListingSlug: "ela-50-plus-adult-senior-programs",
    sourceUrl: "https://elatownship.gov/departments/seniors/",
    blurb:
      "One of Lake Zurich's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp: "Call (847) 438-9160 — Join through the CommunityPass portal at register.capturepoint.com/ElaTownship.",
    tags: null,
  },
  {
    slug: "bulk-westmont-park-district-senior-programs",
    name: "Westmont Park District Senior Programs",
    group: "park-district",
    county: "DuPage",
    existingListingSlug: "westmont-park-district-senior-programs",
    sourceUrl: "https://www.westmontparks.org/programs/senior-programs/",
    blurb:
      "One of Westmont's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call 630-969-8080 ext. 104 — Newsletter subscription $6/yr resident, $9/yr non-resident; most in-center activities free/drop-in",
    tags: null,
  },
  {
    slug: "bulk-patty-turner-senior-center",
    name: "Patty Turner Senior Center",
    group: "township-senior-center",
    county: "Lake",
    existingListingSlug: "patty-turner-senior-center",
    sourceUrl: "https://www.deerfieldparks.org/202/Patty-Turner-Center",
    blurb:
      "One of Deerfield's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call 847-940-4010 — Membership-based; see the PTC Bulletin/Calendar or contact the center directly.",
    tags: null,
  },
  {
    slug: "bulk-active-adults-55-hampshire-township-park-district",
    name: "Active Adults 55+ — Hampshire Township Park District",
    group: "park-district",
    county: "Kane",
    existingListingSlug: "active-adults-55-hampshire-township-park-district",
    sourceUrl: "https://www.hampshireparkdistrict.org/programs-and-events/active-adults-55/",
    blurb:
      "One of Hampshire's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call (847) 683-2690 — Via online catalog (registerc.parksreconline.com)",
    tags: null,
  },
  {
    slug: "bulk-zion-park-district-55-programs",
    name: "Zion Park District 55+ Programs",
    group: "park-district",
    county: "Lake",
    existingListingSlug: "zion-park-district-55-plus-programs",
    sourceUrl: "https://zionparkdistrict.com/wp-content/uploads/2026/04/Summer26SeniorPages.pdf",
    blurb:
      "One of Zion's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 847-746-5500",
    tags: null,
  },
  {
    slug: "bulk-niles-senior-center",
    name: "Niles Senior Center",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "niles-senior-center",
    sourceUrl: "https://www.vniles.com/197/Senior-Services",
    blurb:
      "One of Niles's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp: "Call 847-588-8420 — Register online, in person, or by phone; membership application available online",
    tags: null,
  },
  {
    slug: "bulk-oak-brook-park-district-pioneer-programs-60",
    name: "Oak Brook Park District Pioneer Programs (60+)",
    group: "park-district",
    county: "DuPage",
    existingListingSlug: "oak-brook-park-district-pioneer-programs-60-plus",
    sourceUrl: "https://www.obparks.org/programs/recreation/pioneer-programs-age-60",
    blurb:
      "One of Oak Brook's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call (630) 990-4233 — Online registration via activecommunities.com",
    tags: null,
  },
  {
    slug: "bulk-west-chicago-park-district-adult-senior-programs-50",
    name: "West Chicago Park District Adult & Senior Programs (50+)",
    group: "park-district",
    county: "DuPage",
    existingListingSlug: "west-chicago-park-district-adult-senior-programs-50-plus",
    sourceUrl: "https://www.we-goparks.org/adult-programs",
    blurb:
      "One of West Chicago's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 630.231.9474 — Pre-registration required for all social gatherings and trips",
    tags: null,
  },
  {
    slug: "bulk-palos-heights-senior-adult-programs",
    name: "Palos Heights Senior & Adult Programs",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "palos-heights-senior-adult-programs",
    sourceUrl: "https://palosheights.org/277/Adult-Programs",
    blurb:
      "One of Palos Heights's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 708-361-1800",
    tags: null,
  },
  {
    slug: "bulk-troy-township-senior-program",
    name: "Troy Township Senior Program",
    group: "township-senior-center",
    county: "Will",
    existingListingSlug: "troy-township-senior-program",
    sourceUrl: "https://troytownship.com/senior-activities/",
    blurb:
      "One of Shorewood's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Residents only (based on listing data)",
    howToSignUp: "Call 815-744-1968 — Meal reservations required 1 week ahead; general attendance appears drop-in",
    tags: null,
  },
  {
    slug: "bulk-grayslake-senior-activity-center",
    name: "Grayslake Senior Activity Center",
    group: "township-senior-center",
    county: "Lake",
    existingListingSlug: "grayslake-senior-activity-center",
    sourceUrl: "https://www.villageofgrayslake.com/859/Senior-Activity-Center",
    blurb:
      "One of Grayslake's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call (773) 366-8888 — Download the membership form from the village website or contact the center directly.",
    tags: null,
  },
  {
    slug: "bulk-western-springs-senior-center",
    name: "Western Springs Senior Center",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "western-springs-senior-center",
    sourceUrl: "https://www.wsprings.com/682/Senior-Center",
    blurb:
      "One of Western Springs's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp: "Call 708-246-3299 — Annual membership required to participate in center activities",
    tags: null,
  },
  {
    slug: "bulk-grayslake-park-district-active-adults",
    name: "Grayslake Park District Active Adults",
    group: "park-district",
    county: "Lake",
    existingListingSlug: "grayslake-park-district-active-adults",
    sourceUrl: "https://www.glpd.com/active-adults/",
    blurb:
      "One of Grayslake's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp:
      "Call (847) 223-7529 — Register online through the park district's registration portal; contact Shelly Regnier at sregnier@glpd.com for trip details.",
    tags: null,
  },
  {
    slug: "bulk-social-seniors-program-worth-park-district",
    name: "Social Seniors Program — Worth Park District",
    group: "park-district",
    county: "Cook",
    existingListingSlug: "social-seniors-program-worth-park-district",
    sourceUrl: "https://www.worthparkdistrict.org/adults",
    blurb:
      "One of Worth's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call (708) 448-7080 — Required for Senior Lunch & Bingo and Senior Meet & Eat trips; not required for Friendship Club or Pinochle Club",
    tags: null,
  },
  {
    slug: "bulk-the-east-wing-glenview-senior-center",
    name: "The East Wing Glenview Senior Center",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "east-wing-glenview-senior-center",
    sourceUrl: "https://glenviewparks.org/facilities/the-east-wing-glenview-senior-center/",
    blurb:
      "One of Glenview's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call 847-724-4793 — Register online, by phone, or in person; membership required for most programs",
    tags: null,
  },
  {
    slug: "bulk-mallinckrodt-community-center",
    name: "Mallinckrodt Community Center",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "mallinckrodt-community-center",
    sourceUrl: "https://wilmettepark.org/mallinckrodt-center/mallinckrodt-membership/",
    blurb:
      "One of Wilmette's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call (847) 256-9623 — Sign up online through the park district's registration system or contact the Center Manager",
    tags: null,
  },
  {
    slug: "bulk-the-levy-senior-center-dupage-township",
    name: "The Levy Senior Center (DuPage Township)",
    group: "township-senior-center",
    county: "Will",
    existingListingSlug: "levy-senior-center-dupage-township",
    sourceUrl: "https://dupagetownship.com/seniors/",
    blurb:
      "One of Bolingbrook's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Residents only (based on listing data)",
    howToSignUp: "Call (630) 759-3411 — Free membership application completed in person during business hours",
    tags: null,
  },
  {
    slug: "bulk-highland-park-park-district-55-monthly-meetings",
    name: "Highland Park Park District 55+ Monthly Meetings",
    group: "park-district",
    county: "Lake",
    existingListingSlug: "highland-park-park-district-55-plus-monthly-meetings",
    sourceUrl: "https://highlandparks.org/programs/",
    blurb:
      "One of Highland Park's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "See official site for current schedule and registration",
    tags: null,
  },
  {
    slug: "bulk-linda-jackson-center-for-senior-citizens-glendale-heights",
    name: "Linda Jackson Center for Senior Citizens (Glendale Heights)",
    group: "township-senior-center",
    county: "DuPage",
    existingListingSlug: "linda-jackson-center-for-senior-citizens-glendale-heights",
    sourceUrl: "https://www.glendaleheights.org/170/Linda-Jackson-Center-for-Senior-Citizens",
    blurb:
      "One of Glendale Heights's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 630-260-6050",
    tags: null,
  },
  {
    slug: "bulk-rakow-center-adult-activity-center-dundee-township-park-district",
    name: "Rakow Center Adult Activity Center — Dundee Township Park District",
    group: "park-district",
    county: "Kane",
    existingListingSlug: "rakow-center-adult-activity-center-dundee-township-park-district",
    sourceUrl: "https://www.dtpd.org/adult-50-programs",
    blurb:
      "One of Carpentersville's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp: "Call 847-428-7131 ext. 1101 — Varies by activity — some drop-in, some require registration and a fee",
    tags: null,
  },
  {
    slug: "bulk-the-community-house-active-adults-hinsdale",
    name: "The Community House Active Adults (Hinsdale)",
    group: "township-senior-center",
    county: "DuPage",
    existingListingSlug: "the-community-house-active-adults-hinsdale",
    sourceUrl: "https://thecommunityhouse.org/programs/",
    blurb:
      "One of Hinsdale's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call 630-323-7500 ext. 253 — Contact Jillian Spizzirri or register via the Active Adults Programs portal",
    tags: null,
  },
  {
    slug: "bulk-wayne-township-senior-center",
    name: "Wayne Township Senior Center",
    group: "township-senior-center",
    county: "DuPage",
    existingListingSlug: "wayne-township-senior-center",
    sourceUrl: "https://www.waynetwp-il.org/seniors/",
    blurb:
      "One of West Chicago's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Residents only (based on listing data)",
    howToSignUp: "Call 630-231-7155",
    tags: null,
  },
  {
    slug: "bulk-franklin-park-senior-lunch-program",
    name: "Franklin Park Senior Lunch Program",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "franklin-park-senior-lunch-program",
    sourceUrl: "https://www.villageoffranklinpark.com/departments/health/lunch_for_seniors/",
    blurb:
      "One of Franklin Park's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Verify — see official site",
    howToSignUp: "Call (847) 678-8777 — Walk in and pick up a monthly menu; call for info",
    tags: null,
  },
  {
    slug: "bulk-wauconda-park-district-active-seniors-55",
    name: "Wauconda Park District Active Seniors (55+)",
    group: "park-district",
    county: "Lake",
    existingListingSlug: "wauconda-park-district-active-seniors-55-plus",
    sourceUrl: "https://www.waucondaparks.com/programs/active-adults/",
    blurb:
      "One of Wauconda's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Open to residents and non-residents (based on listing data)",
    howToSignUp:
      "Call 847-526-3610 — Register online using activity codes, or call 847-526-3610 (contact: Stephanie Marconi).",
    tags: null,
  },
  {
    slug: "bulk-schaumburg-township-disability-senior-services",
    name: "Schaumburg Township Disability & Senior Services",
    group: "township-senior-center",
    county: "Cook",
    existingListingSlug: "schaumburg-township-disability-senior-services",
    sourceUrl: "https://schaumburgtownship.org/services/disability-senior-services/",
    blurb:
      "One of Hoffman Estates's senior programs, confirmed to run day trips for older adults — see the full listing for what's been verified.",
    cost: "Varies — see current schedule",
    whoCanJoin: "Residents only (based on listing data)",
    howToSignUp: "Call 847-285-4541 — Appointments required for most services",
    tags: null,
  },
];
